-- V1: Core continuity_plans table
-- Works with both H2 (local dev) and PostgreSQL (Docker/prod)

CREATE TABLE IF NOT EXISTS continuity_plans (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255)    NOT NULL,
    description TEXT,
    status      VARCHAR(50)     NOT NULL DEFAULT 'Pending',
    priority    VARCHAR(50)              DEFAULT 'Medium',
    owner       VARCHAR(255),
    department  VARCHAR(255),
    rto_hours   INTEGER,
    rpo_hours   INTEGER,
    score       INTEGER                  DEFAULT 50,
    deleted     BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Speed up common queries
CREATE INDEX IF NOT EXISTS idx_plans_status     ON continuity_plans (status);
CREATE INDEX IF NOT EXISTS idx_plans_deleted    ON continuity_plans (deleted);
CREATE INDEX IF NOT EXISTS idx_plans_department ON continuity_plans (department);
CREATE INDEX IF NOT EXISTS idx_plans_priority   ON continuity_plans (priority);
