-- V2: Audit log table — records every CREATE, UPDATE, DELETE
-- Populated automatically by AuditAspect.java via AuditLogService

CREATE TABLE IF NOT EXISTS audit_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action       VARCHAR(50)  NOT NULL,        -- CREATE | UPDATE | DELETE
    entity_type  VARCHAR(100) NOT NULL,        -- e.g. "ContinuityPlan"
    entity_id    BIGINT,                       -- ID of the affected record
    details      TEXT,                         -- Human-readable description
    performed_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_action      ON audit_log (action);
CREATE INDEX IF NOT EXISTS idx_audit_entity_id   ON audit_log (entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_performed   ON audit_log (performed_at);
